mathjax: true
math_engine: mathjax
usemath: true

title: My Great Website
author: Cheng Tan
description: A cool website with nothing
# logo: /assets/img/logo.png

# navigation bar
navigation:
  - title: Home
    url: /
  - title: Project 1
    url: /project_1/


# theme: jekyll-theme-cayman
remote_theme: daattali/beautiful-jekyll@master
plugins:
  - jekyll-remote-theme
  - jekyll-include
  - jekyll-seo-tag
include:
  - _includes/head-custom.html


show_downloads: "false"

